#cloud-config
ssh_pwauth: no

users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "${SSH_KEY}"

write_files:
  - content: |
      #!/bin/bash
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      usermod -aG docker user
    path: /root/install-docker.sh
    permissions: "0740"

runcmd:
  - bash /root/install-docker.sh > /var/log/docker-install.log 2>&1